global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'User Service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9095']
        labels:
          application: 'User Service'